#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FORWARD 	1 << 0
#define LEFT		1 << 0

task main()
{
  long x, y, direction;
  ubyte direction_x, direction_y;
  string displayx, displayy, displayz;

  nMotorPIDSpeedCtrl[motorA] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;
  nSyncedMotors = synchNone;
  nSyncedMotors = synchBC;
  nSyncedTurnRatio = +100;

  nMotorEncoder[motorA] = 0;

  while(true)
  {
  	x = y = direction = 0;
    x = messageParm[0];
    y = messageParm[1];
    direction = messageParm[2];

    direction_x = (direction & 0xf0) >> 4;
    direction_y = (direction & 0x0f);

    if (y > 0)
    {
    	if (direction_y & FORWARD)
    		motor[motorB] = -(y);
    	else
    		motor[motorB] = y;
    }
    else
    {
    	motor[motorB] = 0;
    }

    if (x > 0)
    {
    	if (direction_x & LEFT)
    	{
    		if (nMotorEncoder[motorA] < -35)
    			motor[motorA] = 0;
    		else
    			motor[motorA] = -(x);
    	}
    	else
    	{
    		if (nMotorEncoder[motorA] > 35)
    			motor[motorA] = 0;
    		else
    			motor[motorA] = x;
    	}
    }
    else
    {
    	motor[motorA] = 0;
    }

    //Formats the variables into a 'Value x: ' format and displays each on a seperate line
    stringFormat(displayx, "Value x: %d", x);
    stringFormat(displayy, "Value y: %d", y);
    stringFormat(displayz, "Value z: %d", direction);

    displayCenteredTextLine(0, displayx);
    displayCenteredTextLine(2, displayy);
    displayCenteredTextLine(4, displayz);
    ClearMessage();

    wait1Msec(300);
  }
}
